### ISSUE TITLE
chance to have the mod to be ported up to 1.18.2?

### ISSUE THREAD

**Issue by VirtualGaming1** [CAS-ual-TY/YgoDuelingMod#12]
I just want to ask if you are able to port to 1.18.2. this is my latest modpack I use this mod to have fun (plus I like to play YGO in minecraft with friends).

**Comment by CAS-ual-TY** [comment]
no. It is not worth doing that for me. Investing the time into other mods yields a lot better results for me, I am sorry. If you want to know further, please ask on the discord and I will elaborate
