### ISSUE TITLE
In game card images won't load even if enabled.

### ISSUE THREAD

**Issue by FurthestBen** [CAS-ual-TY/YgoDuelingMod#8]
![image](https://user-images.githubusercontent.com/45422986/135666293-4273e260-f883-475d-8985-c0ec78aee0e9.png)
Even when I've set everything up.
Downloaded all the images in the "KingdomsMC - Duelist Kingdoms" server.
The images of cards won't load, but the sets image will.

I've tried restarting the game, redownloading the game, restarting my PC, checking all the text in the files, changing sizes of the cards.
Nothing works. So I image it is a bug.

I've tried this with the technic laugher and manual install.
Windows 10 - 64 bit home
![image](https://user-images.githubusercontent.com/45422986/135666771-efdbcee1-ce8e-4cf0-9f76-cdc74e3f1269.png)
The only conclusion I can say is the mod isn't reading the cards folder correctly.
I am not the only one with this issue, multiple people on this server have the same issue.

**Comment by CAS-ual-TY** [comment]
I need the latest.log file or debug.log file (or both) right after you started Minecraft and hit the main menu.
The cards folder is read correctly but likely a card file didnt set a proper image file or an image file is corrupted.

**Comment by LuisRavenFlame** [comment]
How strong is your computer because it might be that your computer isn't strong enough to handle the images because i use that same format on my server DuelingMC Reborn and it works just fine for everyone on my server.

**Comment by MattAlpha972** [comment]
Hi There, i Don't know if That page Is still working but i Try at least, i have Bean using the mod for a long time, and recentely the image of cards stop loading it's even start before i update the mod so i wanted to ask ''What i have to do to make the image work again?''

**Comment by CAS-ual-TY** [comment]
@MattAlpha972 it was fixed. If it still does not work reopen this.
